### ISSUE TITLE
UART TX buffer

### ISSUE THREAD

**Issue by theBASTI0N** [ruuvi/ruuvi.gateway_nrf.c#1]
If the Ruuvi filter is removed some beacon output will be outputed onto two lines. Issue can be resolved by setting the buffer to 512

**Comment by ojousima** [comment]
Thanks for reporting the issue, is it already resolved or why did you close it?

**Comment by theBASTI0N** [comment]
I flashed another board and didnt have that issue anymore. So i tried two more board and then the original board, only ever had an issue on the first board so not sure what is wrong. But everything worked as expected on the other units.

Increasing the buffer on the faulty board helped with the issue but it would still occur.
