### ISSUE TITLE
Documentation: Add example sequences for communication 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_nrf.c#16]
Under https://docs.ruuvi.com/ruuvi-gateway-firmware/gw-nrf52-firmware/gw-nrf52811-uart-communication, ask me for write access

**Comment by opsationby** [comment]
fix by https://github.com/ruuvi/docs/commit/8ab56fb7d6a1a54ad14397b5043130a92522ad0f

**Comment by ojousima** [comment]
Thanks
