### ISSUE TITLE
report startup and config via syslog - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_nrf.c#43]
syslog should be uset to report version, initalization and configuration of both the nRF and  esp modules

It is very important, especially during development and **initial deployment**, for a system to announce its version.
This indicates the not only has the process has sucessfully started but also which version has been started.

Syslog is a trival means developed for just this type of information. If the UDP (User Datagram Protocol) is used it is
non  blocking and (nearly) infalible (from the point of viewn of the initating proess).
The syslog server reported to can be a static IP address, a static hostname, retrieved from the DCHP information
(currently providing the systems IP address, gateway, DNS serve)r or it can be provided during setup similar to the
definiton of the host server for the Ruuvi server(less). It could even be set to a Ruuvi syslog server temporarily during initial deployment and if there were a problem!
While LOG message to the USB port are important for initial development, 
syslog messasages suggested can be very important during deployment to confirm that the expected configuration is actually
in use and that basic functionalality is working. For example upstream network is alive and packets are being sent.
The syslog messages can be stored at the syslog server and/or forwarded to another system. These message can be
important in fault detection and isolation. Even coordinating previous faults with other events.
Printers, Routers use this (even my remote swamp and retirement home monitors use it)

This information is already available for LOG and should be sent via syslog as well.
Gateway SETTINGS:  (details supressed if using=0, minimal length string i.e. few syntactical elements i.e. not JSON)
using eth:0; dhcp:1; static ip:NA; netmask:NA; gw:NA; dns1:NA; dns2: NA
using mqtt:0; server:NA; port:0; prefix:NA; user: mqtt
using http:1; url:https://network.ruuvi.com/record ; user:NA
coordinates: ????
company id filter: 1; id: 0x0499
scan coded phy: 0; scan 1mbit/phy: 1; extended payload: 1 channel 37: 1 38: 1 39: 1
My hostname:RuuviGatewayD828

**Comment by ojousima** [comment]
This would be more relevant to the gateway_esp, nrf52811 is so resource constrained that there is no room for any extra log/debug information
